INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Real Madrid', 'La Liga', 'España');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('FC Barcelona', 'La Liga', 'España');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Manchester United', 'Premier League', 'Inglaterra');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Liverpool FC', 'Premier League', 'Inglaterra');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Juventus FC', 'Serie A', 'Italia');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('AC Milan', 'Serie A', 'Italia');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Bayern Munich', 'Bundesliga', 'Alemania');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Borussia Dortmund', 'Bundesliga', 'Alemania');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Paris Saint-Germain', 'Ligue 1', 'Francia');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Olympique de Marseille', 'Ligue 1', 'Francia');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('FC Porto', 'Primeira Liga', 'Portugal');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Sporting CP', 'Primeira Liga', 'Portugal');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Ajax Amsterdam', 'Eredivisie', 'Países Bajos');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Feyenoord', 'Eredivisie', 'Países Bajos');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Celtic FC', 'Scottish Premiership', 'Escocia');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Rangers FC', 'Scottish Premiership', 'Escocia');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Galatasaray SK', 'Süper Lig', 'Turquía');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Fenerbahçe SK', 'Süper Lig', 'Turquía');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('FC Zenit Saint Petersburg', 'Premier League Rusa', 'Rusia');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Spartak Moscow', 'Premier League Rusa', 'Rusia');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('SL Benfica', 'Primeira Liga', 'Portugal');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Besiktas JK', 'Süper Lig', 'Turquía');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('SSC Napoli', 'Serie A', 'Italia');
INSERT INTO TEAM (NAME, LEAGUE, COUNTRY) VALUES ('Atlético Madrid', 'La Liga', 'España');
INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (1, 'test', '$2a$10$6l5jlp.s/hHZ790DJl5Q8uzcG20x7ofofkexQz/.bL4R5Jko2Hb5m');
