DROP TABLE IF EXISTS TEAM;

CREATE TABLE TEAM (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
LEAGUE VARCHAR(50) NOT NULL,
COUNTRY VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    ID INT NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);